name: Freeze plugin
version: 1.1
main: me.beatcomet.Freeze.Frz
description:
commands:
   freeze:
      aliases: f
      description: This Command freezes a player
      usage: /<command> [player]
   check:
      description: This command checks if player is freezed
      usage: /<command> [Player]
   status:
      description: This command gets online players status
      usage: /<command> [Player]